http:
  routers:
    registry:
      rule: "Host(`registry.localhost`)"
      service: registry
    registry-ui:
      rule: "Host(`registry-ui.localhost`)"
      service: registry-ui
  services:
    registry:
      loadBalancer:
        servers:
          - url: "http://localhost:50000"
    registry-ui:
      loadBalancer:
        servers:
          - url: "http://localhost:49159"
